# pyinstaller 로 exe 를 build 하기 위한 설정

# 1. 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 2. 데이타 파일들을 지정하세요. 현재 working folder 에 들어있는.
data_files = [
    'archer_shoot.png',
    'arrow.png',
    'backdrop_canvas.png',
    'backdrop_hills.png',
    'backdrop_rocks.png',
    'beggar.png',
    'boss_bash_left.png',
    'boss_bash_right.png',
    'boss_death.png',
    'boss_idle.png',
    'boss_walk.png',
    'box.png',
    'bunny.png',
    'campfire.png',
    'citizen.png',
    'coin.png',
    'deer_die.png',
    'deer_idle.png',
    'deer_run.png',
    'deer_walk.png',
    'farmland.png',
    'fog.png',
    'game_over.png',
    'hills_02.png',
    'hills_03.png',
    'hills_04.png',
    'king.png',
    'level0_base.png',
    'level1_base.png',
    'level2_base.png',
    'level3_base.png',
    'level4_base.png',
    'level5_base.png',
    'npc_run_sprite.png',
    'npc_wait_sprite.png',
    'npc_walk_sprite.png',
    'portal.png',
    'sack.png',
    'scaffolds_01.png',
    'scaffolds_02.png',
    'scaffolds_03.png',
    'scaffolds_04.png',
    'scaffolds_fill_01.png',
    'scaffolds_fill_02.png',
    'scaffolds_fill_03.png',
    'scaffolds_fill_04.png',
    'shop_bow.png',
    'shop_hammer.png',
    'shop_scythe.png',
    'shop_spear.png',
    'shop_sword.png',
    'sky.png',
    'tiles.png',
    'tools_bow.png',
    'tools_hammer.png',
    'tools_scythe.png',
    'treeline.png',
    'troll_charge.png',
    'troll_die.png',
    'troll_walk.png',
    'wall.png',
    'wall_bg_stone_0.png',
    'wall_bg_stone_1.png',
    'wall_bg_stone_2.png',
    'wall_bg_wood_0.png',
    'wall_bg_wood_1.png',
    'wall_bg_wood_2.png',
    'water.png',
    'DeterminationSansK2.ttf',
    'ENCR10B.TTF',
    'archer_shoot_v2.wav',
    'archer_totowerlp2.wav',
    'arrow_hit_bunny.wav',
    'arrow_kill_troll.wav',
    'Bloom.wav',
    'castle_upgrade_1.wav',
    'castle_upgrade_2.wav',
    'castle_upgrade_3lp.wav',
    'castle_upgrade_4.wav',
    'castle_upgrade_5.wav',
    'citizen_picksup_coin.wav',
    'coin_drophitground.wav',
    'player_walk_dirt.wav',
    'troll_hitwall4_v2.wav'
]

# 3. 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [

]

